version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
  fxrabbitmqservice:
    image: fxrabbitmqserviece:0.1
  fxnotificationservice:
    image: fxnotificationservice:0.1
  fxratesmonitor:
    image: fxratesmonitor:0.1
  fxeventsmonitor:
    image: fxeventsmonitor:0.1
